### ISSUE TITLE
Wrong information in README.md

### ISSUE THREAD

**Issue by Dreadwin** [kajic/jquery-animateNumber#6]
The README file reads the following: 

currencyDecimalSeparator: The character to be inserted between groups of thousands when displaying currency. The default value is determined by the browser's current locale.

currencyDecimalSeparator: The character to be inserted between the integer and decimal values when displaying currency. The default value is determined by the browser's current locale.

Which should be:

**currencyGroupSeparator**: The character to be inserted between groups of thousands when displaying currency. The default value is determined by the browser's current locale.

currencyDecimalSeparator: The character to be inserted between the integer and decimal values when displaying currency. The default value is determined by the browser's current locale.

**Comment by danbovey** [comment]
+1
